---
title: "MA376 Lesson 1"
author: "Clark"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Contact Information

LTC Nick Clark

nicholas.clark@westpoint.edu

Thayer Hall Room 249

845-938-7461

#Course Overview

\textit{Mathematical } Statistics

-Review of Probabilitiy

-Comon density functions, operations involving density functions

-Functions of Random Variables (what is a random variable?)

-Parameter estimation techniques

-Evaluation of estimation techniques

-Properties of point esitimators

-Hypothesis testing

#Set Notation

A picture: 
\vspace{.5in}

$S=\{s_1,s_2,s_3,s_4\}$

We can write: $s_1 \in S$

$A=\{s_1,s_3\}$

We can write: 

$B=\{s_2,s_4\}$

$A\cup B=$    

$A \cap B=$

Oftentimes Venn Diagrams help us understand what is going on.  For example, DeMorgan's Laws state:
\begin{align*}
\overline{A \cap B}=\overline{A} \cup \overline{B} \\
\overline{A \cup B}=\overline{A} \cap \overline{B}
\end{align*}
picture:
\vspace{2.in}

#Problem 2.7 in WMS

Now.  None of this has anything to do with probability or statistics.  Set theory is a tool, like Caculus is a tool, that can potentially help us.  But let's go back to probability theory.  We are going to define a \textbf{Probability Space} which consissts of three things.  A sample space, a list of events we are potentially interested in, and probabilities of those events occurring.  We will start with \textbf{Discrete } outcomes.

Sample space: $S=\{\mbox{Roll a 1}, \mbox{Roll a 2}, \mbox{Roll a 3}, \mbox{Roll a 4}, \mbox{Roll a 5}, \mbox{Roll a 6}\}$

Allowable events (technically must be a $\sigma-$Algebra )

What are some events we might be interested in?  For any events, $A$ and $B$, what can we say about $A \cup B$?  What about $\overline{A}$?  

\vspace{.5in}

Simple events vs. compound events.

#Probability
Last part of our probability space.  What is probability?

Technically a probability is a set function that \textit{measures} an event.  Let's look at \textbf{Definition 2.6}.  

One way to assign a probability to a discrete sample space is to use relative frequency of each simple event. 

\newpage

Let's put this all together:

\vspace{5.in}

Now, we have our discrete sample space, a way to come up with events of interest (any set  $A\subset S$), and a way to assign probabilities to $A$.

#Admin
Introductions

Homework

Next Lesson

#Start with 2.18 in WMS
